#!/bin/bash
#NOTE: DO NOT EDIT THIS FILE-- MAY RESULT IN INCOMPLETE SUBMISSIONS

NOTEBOOKS="FullyConnectedNets.ipynb
BatchNormalization.ipynb
Dropout.ipynb
ConvolutionalNetworks.ipynb
PyTorch.ipynb
TensorFlow.ipynb"

CODE="cs231n/layers.py
cs231n/classifiers/fc_net.py
cs231n/optim.py
cs231n/classifiers/cnn.py"

ZIP_FILENAME="a2.zip"

FILES="${NOTEBOOKS} ${CODE}"
for FILE in ${FILES}
do
	if [ ! -f ${FILE} ]; then
		echo "Required file ${FILE} not found, Exiting."
		exit 0
	fi
done

echo "### Zipping file ###"
zip -r ${ZIP_FILENAME} . -x "*.git*" "*cs231n/datasets*" "*.ipynb_checkpoints*" "*README.md" "collectSubmission.sh" "*requirements.txt" "*__pycache__*" ".env/*" > assignment_zip.log
echo ""

echo "Please rename ${ZIP_FILENAME} into a2_<AU-username>_<first-name>_<last-name>.zip and upload to Canvas."
